/**
 * @description define the navigation routes name by key
 */
export enum Routes {
  DetailGarage = 'DetailGarage',
  VehicleRental = 'VehicleRental',
  AllCategories = 'AllCategories',
  InputPhone = 'InputPhone',
  Register = 'Register',
  Intro = 'Intro',
  HomeTabs = 'HomeTabs',
  HomeTabsLogin = 'HomeTabsLogin',
  Profile = 'Profile',
  Home = 'Home',
  Message = 'Message',
  SuggestForYou = 'SuggestForYou',
  OTP = 'OTP',
  KYC = 'KYC',
  ResetPassword = 'ResetPassword',
  InputPassword = 'InputPassword',
  Promotion = 'Promotion',
  Activity = 'Activity',
  // Map
  Delivery = 'Delivery',
  shipment = 'shipment',
  FindCar = 'FindCar',
  InputAddress = 'InputAddress',
  // Order
  Orders = 'Orders',
  Notification = 'Notification',
  Menu = 'Menu',
  OrderDetail = 'OrderDetail',
  HistoryOrderDetail = 'HistoryOrderDetail',

  //Account
  Account = 'Account',
  RestaurantInfo = 'RestaurantInfo',
  OperatingTime = 'OperatingTime',
  Contact = 'Contact',
  Address = 'Address',
  Helpers = 'Helpers',
  BankAccount = 'BankAccount',
  ChangePassword = 'ChangePassword',
  AddMenu = 'AddMenu',

  Porposed = 'Porposed',
  Categories = 'Categories',
  CartOrder = 'CartOrder',
  CartOrderVehicle = 'CartOrderVehicle',
  CheckOrder = 'CheckOrder',
  ExtraFood = 'ExtraFood',
  ExtraVehicle = 'ExtraVehicle',
  MethodPayment = 'MethodPayment',
  BikeMethodPayment = 'BikeMethodPayment',
  Promotion = 'Promotion',
  RestaurantDetail = 'RestaurantDetail',
  DeliveryAddress = 'DeliveryAddress',
  HistoryActivity = 'HistoryActivity',
  Biker = 'Biker',

  ContactSupport = 'ContactSupport',
  InfoUser = 'InfoUser',
  Term = 'Term',
  RequestDelivery = 'RequestDelivery',
  Rating = 'Rating',
  RatingBiker = 'RatingBiker',
  RatingRestaurant = 'RatingRestaurant',
  MessageDetail = 'MessageDetail',

  ModalScreen = 'ModalScreen',

  Wallet = 'Wallet',
  HistoryWallet = 'HistoryWallet',
  WithdrawPoints = 'WithdrawPoints',
  TopUpPoint = 'TopUpPoint',
}
